version: '3.3'
services:
  auth-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: auth-db
      MYSQL_USER: user
      MYSQL_PASSWORD: Personal@123456
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3307:3306
    volumes:
      - auth-mysql-db:/var/lib/mysql

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

volumes:
  auth-mysql-db: